export const movieArray= [
    {
    "_id": "65ef41ed675dde80108d736d",
    "id": 1219487,
    "title": "Les Dalton courent toujours",
    "vote_average": 0,
    "vote_count": 0,
    "status": "Released",
    "revenue": 0,
    "runtime": 0,
    "adult": false,
    "budget": 0,
    "original_language": "fr",
    "original_title": "Les Dalton courent toujours",
    "popularity": 0,
    "poster_path": "https://image.tmdb.org/t/p/original//yyXDrnChnYlTd5bV7vwIVcHrJWr.jpg",
    "spoken_languages": "French"
},
{
    "_id": "65ef43b8675dde8010930f0e",
    "id": 811951,
    "title": "Pedro Páramo",
    "vote_average": 0,
    "vote_count": 0,
    "status": "Released",
    "release_date": "2021-03-29T00:00:00.000Z",
    "revenue": 0,
    "runtime": 98,
    "adult": false,
    "budget": 0,
    "original_language": "en",
    "original_title": "Pedro Páramo",
    "overview": "A son returns home to meet his father and reveals how one man’s unchecked appetite destroys both everything he loves and the town that made him great.",
    "popularity": 0.612,
    "poster_path": "https://image.tmdb.org/t/p/original//sjeDSBHQKyk7AW2ASfpjQwpomvf.jpg",
    "production_companies": "Goodman Theatre"
},
{
    "_id": "65ef3f8a675dde8010860669",
    "id": 18742,
    "title": "The House Next Door",
    "vote_average": 5,
    "vote_count": 17,
    "status": "Released",
    "release_date": "2006-10-30T00:00:00.000Z",
    "revenue": 0,
    "runtime": 86,
    "adult": false,
    "budget": 0,
    "imdb_id": "tt0863080",
    "original_language": "en",
    "original_title": "The House Next Door",
    "overview": "Walker Kennedy and his wife Col are a happy, voluntarily childless suburban couple. Then the thing they fear the most happens: part of their green surrounding is turned into a building site, for what turns out to be the widely acclaimed first house built by attractive, brilliant, obsessively devoted architect Kim (30), who has a short affair with Col. Kim is even enchanted by his own house, just like everyone else. However each subsequent couple that moves into the house soon turns nasty, never staying for long, ending in tears and/or blood. When Kim finally buys it with his wife, Col who believes he somehow curses all his buildings insists it's time to deal with him, permanently.",
    "popularity": 2.517,
    "poster_path": "https://image.tmdb.org/t/p/original//eNuwHk9GbXKcDxF91JZHiH6927H.jpg",
    "genres": "Horror, Mystery, Thriller",
    "production_companies": "Barbara Lieberman Productions, CBS Studios, Muse Entertainment, Lifetime",
    "production_countries": "Canada, United States of America",
    "spoken_languages": "English"
},
{
    "_id": "65ef4420675dde80109456b2",
    "id": 646967,
    "title": "The PM, the Playboy and the Wolf of Wall Street",
    "vote_average": 0,
    "vote_count": 0,
    "status": "Released",
    "release_date": "2019-10-21T00:00:00.000Z",
    "revenue": 0,
    "runtime": 81,
    "adult": false,
    "backdrop_path": "/dIG6YYmo7JVfRIJqEDVLSzPPkXP.jpg",
    "budget": 0,
    "homepage": "https://www.bbc.co.uk/programmes/m0009m7s",
    "original_language": "en",
    "original_title": "The PM, the Playboy and the Wolf of Wall Street",
    "overview": "Investigative reporters examine the 1MDB scandal, tracing money from the Wolf of Wall Street all the way to the Malaysian Prime Minister.",
    "popularity": 0.6,
    "poster_path": "https://image.tmdb.org/t/p/original//bJnML8e7qXbaWrAO41f7J0VIZF.jpg",
    "genres": "Documentary, Crime",
    "production_companies": "BBC Storyville",
    "production_countries": "United Kingdom",
    "spoken_languages": "English, Malay"
},
{
    "_id": "65ef422a675dde80108e4fc4",
    "id": 1055591,
    "title": "Baaghi Ek Yodha",
    "vote_average": 0,
    "vote_count": 0,
    "status": "Released",
    "release_date": "2019-10-04T00:00:00.000Z",
    "revenue": 0,
    "runtime": 162,
    "adult": false,
    "backdrop_path": "/9D5bUyCFWJd6jXfHleVrqx7OwPD.jpg",
    "budget": 0,
    "imdb_id": "tt11238094",
    "original_language": "hi",
    "original_title": "Baaghi Ek Yodha",
    "overview": "Baaghi - Ek Yodha is a Bhojpuri movie released on 4 Oct, 2019. The movie is directed by Shekhar Sharma",
    "popularity": 0.6,
    "poster_path": "https://image.tmdb.org/t/p/original//f6WWjLCFRKLuHaf7tiwn08AGTwa.jpg",
    "genres": "Action, Drama"
},
{
    "_id": "65ef3f48675dde8010855e39",
    "id": 43372,
    "title": "Bellissima",
    "vote_average": 7.826,
    "vote_count": 184,
    "status": "Released",
    "release_date": "1951-12-28T00:00:00.000Z",
    "revenue": 0,
    "runtime": 115,
    "adult": false,
    "backdrop_path": "/edpyhfSsJZLSq2pRb8ffwPpCwK4.jpg",
    "budget": 0,
    "imdb_id": "tt0043332",
    "original_language": "it",
    "original_title": "Bellissima",
    "overview": "Bellissima is a satire of the film industry, and centers on a mother and daughter after the latter attends an audition.",
    "popularity": 9.22,
    "poster_path": "https://image.tmdb.org/t/p/original//d3LmeYvqzeS3oY3zP93jNfYS15O.jpg",
    "genres": "Comedy, Drama",
    "production_companies": "Film Bellissima, CEI Incom",
    "production_countries": "Italy",
    "spoken_languages": "Italian"
},
{
    "_id": "65ef4164675dde80108b846e",
    "id": 883155,
    "title": "Passionate Sex And Creampie With A Schoolgirl 20 Years My Junior, Starring Asuka Hanahara",
    "vote_average": 0,
    "vote_count": 0,
    "status": "Released",
    "release_date": "2021-10-05T00:00:00.000Z",
    "revenue": 0,
    "runtime": 120,
    "adult": true,
    "backdrop_path": "/ph3tDhcEpzgNLMV6gZPRENz0UoI.jpg",
    "budget": 0,
    "original_language": "ja",
    "original_title": "20歳以上も年の離れた制服少女と一心不乱にめちゃくちゃ交尾して中出しした・・・",
    "overview": "Asuka, who works part-time at a family restaurant, is in love with Ippei, an uncle who works at the restaurant. Ippei was a useless middle-aged man who was flattered by the store manager, Hito, every day, but he was kind at heart and always cared about Asuka. Asuka was separated from her father, whom she once loved, and from that memory, she had feelings for Ippei, who resembled her father. Finally lifted the ban on vaginal cum shot! Don't miss the pure love drama with a middle-aged man who experiences the pleasure of sperm being poured into the uterus for the first time!",
    "popularity": 0.6,
    "poster_path": "https://image.tmdb.org/t/p/original//c8s4oClFPPOaTgmtBrhw0z4KnmY.jpg",
    "genres": "Drama",
    "production_companies": "kawaii",
    "production_countries": "Japan",
    "spoken_languages": "Japanese"
},
{
    "_id": "65ef41b0675dde80108c9248",
    "id": 1205073,
    "title": "Vecchi: L'Amfipamaso",
    "vote_average": 0,
    "vote_count": 0,
    "status": "Released",
    "release_date": "2004-05-10T00:00:00.000Z",
    "revenue": 0,
    "runtime": 58,
    "adult": false,
    "budget": 0,
    "homepage": "https://www.chandos.net/products/catalogue/CHDVD%205029",
    "original_language": "it",
    "original_title": "Vecchi: L'Amfipamaso",
    "overview": "The classic music theatre work of the Italian Renaissance, written the same year as the first opera and based on the characters of the commedia dell’arte – old men, cowards, scheming servants and self-obsessed lovers. The slapstick for the comic characters is perfectly balanced by the ravishing Gesualdo-esque writing for the lovers.  Source: https://microsites.ifagiolini.com/recordings/lamfiparnaso/",
    "popularity": 0,
    "poster_path": "https://image.tmdb.org/t/p/original//wgROCxtHEA5Ac0wSoRVkZGr9YRR.jpg",
    "genres": "Music",
    "spoken_languages": "English, Italian"
},
{
    "_id": "65ef4290675dde80108f99ed",
    "id": 416789,
    "title": "The Medal",
    "vote_average": 0,
    "vote_count": 0,
    "status": "Released",
    "release_date": "2016-08-01T00:00:00.000Z",
    "revenue": 0,
    "runtime": 0,
    "adult": false,
    "budget": 0,
    "imdb_id": "tt6112166",
    "original_language": "ru",
    "original_title": "Орден",
    "popularity": 0.875,
    "poster_path": "https://image.tmdb.org/t/p/original//ljpjU8WxEvJZ4iTUCiQnqCbcGln.jpg",
    "genres": "War",
    "production_countries": "Russia",
    "spoken_languages": "Russian"
},{
    "_id": "65ef400c675dde80108767a0",
    "id": 370254,
    "title": "Ambición sangrienta",
    "vote_average": 5,
    "vote_count": 4,
    "status": "Released",
    "release_date": "1968-08-29T00:00:00.000Z",
    "revenue": 0,
    "runtime": 85,
    "adult": false,
    "budget": 0,
    "imdb_id": "tt0235973",
    "original_language": "es",
    "original_title": "Ambición sangrienta",
    "overview": "A lawman and two sidekicks clear up a series of crimes related to mining rights.",
    "popularity": 0.982,
    "genres": "Western, Crime, Action, Adventure",
    "production_companies": "Rosas Films S.A.",
    "production_countries": "Mexico",
    "spoken_languages": "Spanish"
},
{
    "_id": "65ef4164675dde80108b846e",
    "id": 883155,
    "title": "Passionate Sex And Creampie With A Schoolgirl 20 Years My Junior, Starring Asuka Hanahara",
    "vote_average": 0,
    "vote_count": 0,
    "status": "Released",
    "release_date": "2021-10-05T00:00:00.000Z",
    "revenue": 0,
    "runtime": 120,
    "adult": true,
    "backdrop_path": "/ph3tDhcEpzgNLMV6gZPRENz0UoI.jpg",
    "budget": 0,
    "original_language": "ja",
    "original_title": "20歳以上も年の離れた制服少女と一心不乱にめちゃくちゃ交尾して中出しした・・・",
    "overview": "Asuka, who works part-time at a family restaurant, is in love with Ippei, an uncle who works at the restaurant. Ippei was a useless middle-aged man who was flattered by the store manager, Hito, every day, but he was kind at heart and always cared about Asuka. Asuka was separated from her father, whom she once loved, and from that memory, she had feelings for Ippei, who resembled her father. Finally lifted the ban on vaginal cum shot! Don't miss the pure love drama with a middle-aged man who experiences the pleasure of sperm being poured into the uterus for the first time!",
    "popularity": 0.6,
    "poster_path": "https://image.tmdb.org/t/p/original//c8s4oClFPPOaTgmtBrhw0z4KnmY.jpg",
    "genres": "Drama",
    "production_companies": "kawaii",
    "production_countries": "Japan",
    "spoken_languages": "Japanese"
}
]

//<div className={styles.movieDetails}><img src={item.poster_path} alt={`${item.title} Movie Poster`} width={250} height={250}/></div>
//<div className={styles.movieDetails}>{item.title}</div>
//<div className={styles.movieDetails}>{item.release_date? item.release_date.split('-')[0]: 'Not Available'}</div>